// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ACCESS_TOKEN_WEB'] ?? '',
    appId: '1:23833082834:web:45d09879071aab6910e60b',
    messagingSenderId: '23833082834',
    projectId: 'hart-voor-verkeer',
    authDomain: 'hart-voor-verkeer.firebaseapp.com',
    storageBucket: 'hart-voor-verkeer.firebasestorage.app',
    measurementId: 'G-5CSMQD9HZN',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ACCESS_TOKEN_ANDROID'] ?? '',
    appId: '1:23833082834:android:82b24c9b58a4001c10e60b',
    messagingSenderId: '23833082834',
    projectId: 'hart-voor-verkeer',
    storageBucket: 'hart-voor-verkeer.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ACCESS_TOKEN_IOS'] ?? '',
    appId: '1:23833082834:ios:68cd826a5799dc4f10e60b',
    messagingSenderId: '23833082834',
    projectId: 'hart-voor-verkeer',
    storageBucket: 'hart-voor-verkeer.firebasestorage.app',
    iosBundleId: 'com.example.hvvMeldapplicatie',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ACCESS_TOKEN_MACOS'] ?? '',
    appId: '1:23833082834:ios:68cd826a5799dc4f10e60b',
    messagingSenderId: '23833082834',
    projectId: 'hart-voor-verkeer',
    storageBucket: 'hart-voor-verkeer.firebasestorage.app',
    iosBundleId: 'com.example.hvvMeldapplicatie',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ACCESS_TOKEN_WINDOWS'] ?? '',
    appId: '1:23833082834:web:a76f1fb4e0cbfe1c10e60b',
    messagingSenderId: '23833082834',
    projectId: 'hart-voor-verkeer',
    authDomain: 'hart-voor-verkeer.firebaseapp.com',
    storageBucket: 'hart-voor-verkeer.firebasestorage.app',
    measurementId: 'G-ZRJ2NFJ4P6',
  );
}


